<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ElementSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('elements')->insert([
            [
                'number' => 1,
                'symbol' => 'H',
                'name' => 'Hydrogen',
                'atomic_mass' => 1.008,
                'category' => 'Nonmetal',
                'melting_point' => -259.14,
                'boiling_point' => -252.87,
                'group' => 1,
                'period' => 1,
                'description' => 'Hydrogen is the lightest element and most abundant chemical substance in the universe. It is crucial for water and organic compounds.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_001_hydrogen/element_001_hydrogen.glb'
            ],
            [
                'number' => 2,
                'symbol' => 'He',
                'name' => 'Helium',
                'atomic_mass' => 4.0026,
                'category' => 'Noble Gas',
                'melting_point' => -272.2,
                'boiling_point' => -268.93,
                'group' => 18,
                'period' => 1,
                'description' => 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas and has the lowest boiling point of all the elements.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_002_helium/element_002_helium.glb'
            ],
            [
                'number' => 3,
                'symbol' => 'Li',
                'name' => 'Lithium',
                'atomic_mass' => 6.94,
                'category' => 'Alkali Metal',
                'melting_point' => 180.50,
                'boiling_point' => 1330,
                'group' => 1,
                'period' => 2,
                'description' => 'Lithium is a soft, silvery-white alkali metal. It is highly reactive and flammable, and is used in batteries and alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_003_lithium/element_003_lithium.glb'
            ],
            [
                'number' => 4,
                'symbol' => 'Be',
                'name' => 'Beryllium',
                'atomic_mass' => 9.0122,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 1287,
                'boiling_point' => 2471,
                'group' => 2,
                'period' => 2,
                'description' => 'Beryllium is a relatively rare alkaline earth metal known for its high strength-to-weight ratio. It is used in aerospace and nuclear applications.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_004_beryllium/element_004_beryllium.glb'
            ],
            [
                'number' => 5,
                'symbol' => 'B',
                'name' => 'Boron',
                'atomic_mass' => 10.81,
                'category' => 'Metalloid',
                'melting_point' => 2076,
                'boiling_point' => 4000,
                'group' => 13,
                'period' => 2,
                'description' => 'Boron is a metalloid with unique properties. It exists in several allotropes and is used in glass, ceramics, and as a neutron absorber in nuclear reactors.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_005_boron/element_005_boron.glb'
            ],
            [
                'number' => 6,
                'symbol' => 'C',
                'name' => 'Carbon',
                'atomic_mass' => 12.011,
                'category' => 'Nonmetal',
                'melting_point' => 3550,
                'boiling_point' => 4827,
                'group' => 14,
                'period' => 2,
                'description' => 'Carbon is a fundamental element for all known life on Earth. It exists in various forms like diamond, graphite, and fullerenes.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_006_carbon/element_006_carbon.glb'
            ],
            [
                'number' => 7,
                'symbol' => 'N',
                'name' => 'Nitrogen',
                'atomic_mass' => 14.007,
                'category' => 'Nonmetal',
                'melting_point' => -210.00,
                'boiling_point' => -195.79,
                'group' => 15,
                'period' => 2,
                'description' => 'Nitrogen is a colorless, odorless, and mostly inert diatomic gas, making up about 78% of Earth\'s atmosphere. It is essential for proteins and DNA.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_007_nitrogen/element_007_nitrogen.glb'
            ],
            [
                'number' => 8,
                'symbol' => 'O',
                'name' => 'Oxygen',
                'atomic_mass' => 15.999,
                'category' => 'Nonmetal',
                'melting_point' => -218.79,
                'boiling_point' => -182.95,
                'group' => 16,
                'period' => 2,
                'description' => 'Oxygen is a highly reactive nonmetal and a vital component of air, essential for respiration in most living organisms and combustion.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_008_oxygen/element_008_oxygen.glb'
            ],
            [
                'number' => 9,
                'symbol' => 'F',
                'name' => 'Fluorine',
                'atomic_mass' => 18.998,
                'category' => 'Halogen',
                'melting_point' => -219.67,
                'boiling_point' => -188.11,
                'group' => 17,
                'period' => 2,
                'description' => 'Fluorine is the most electronegative element and a highly reactive halogen. It is used in toothpaste (as fluoride) and refrigerants.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_009_fluorine/element_009_fluorine.glb'
            ],
            [
                'number' => 10,
                'symbol' => 'Ne',
                'name' => 'Neon',
                'atomic_mass' => 20.180,
                'category' => 'Noble Gas',
                'melting_point' => -248.59,
                'boiling_point' => -246.08,
                'group' => 18,
                'period' => 2,
                'description' => 'Neon is a noble gas that emits a characteristic reddish-orange light when an electric current is passed through it, widely used in neon signs.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_010_neon/element_010_neon.glb'
            ],
            [
                'number' => 11,
                'symbol' => 'Na',
                'name' => 'Sodium',
                'atomic_mass' => 22.990,
                'category' => 'Alkali Metal',
                'melting_point' => 97.79,
                'boiling_point' => 883,
                'group' => 1,
                'period' => 3,
                'description' => 'Sodium is a soft, silvery-white, highly reactive alkali metal. It is a crucial component of salt (sodium chloride) and plays a vital role in biological systems.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_011_sodium/element_011_sodium.glb'
            ],
            [
                'number' => 12,
                'symbol' => 'Mg',
                'name' => 'Magnesium',
                'atomic_mass' => 24.305,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 650,
                'boiling_point' => 1090,
                'group' => 2,
                'period' => 3,
                'description' => 'Magnesium is a light, silvery-white alkaline earth metal. It is essential for chlorophyll in plants and is used in alloys and fireworks.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_012_magnesium/element_012_magnesium.glb'
            ],
            [
                'number' => 13,
                'symbol' => 'Al',
                'name' => 'Aluminum',
                'atomic_mass' => 26.982,
                'category' => 'Post-Transition Metal',
                'melting_point' => 660.32,
                'boiling_point' => 2470,
                'group' => 13,
                'period' => 3,
                'description' => 'Aluminum is a lightweight, corrosion-resistant post-transition metal. It is the most abundant metal in the Earth\'s crust and widely used in construction, transportation, and packaging.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_013_aluminum/element_013_aluminum.glb'
            ],
            [
                'number' => 14,
                'symbol' => 'Si',
                'name' => 'Silicon',
                'atomic_mass' => 28.085,
                'category' => 'Metalloid',
                'melting_point' => 1414,
                'boiling_point' => 3265,
                'group' => 14,
                'period' => 3,
                'description' => 'Silicon is a metalloid and the second most abundant element in the Earth\'s crust. It is the primary component of semiconductors used in electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_014_silicon/element_014_silicon.glb'
            ],
            [
                'number' => 15,
                'symbol' => 'P',
                'name' => 'Phosphorus',
                'atomic_mass' => 30.974,
                'category' => 'Nonmetal',
                'melting_point' => 44.15,
                'boiling_point' => 280,
                'group' => 15,
                'period' => 3,
                'description' => 'Phosphorus is a reactive nonmetal existing in several allotropes (white, red, black). It is essential for DNA, RNA, and energy transfer in living organisms.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_015_phosphorus/element_015_phosphorus.glb'
            ],
            [
                'number' => 16,
                'symbol' => 'S',
                'name' => 'Sulfur',
                'atomic_mass' => 32.06,
                'category' => 'Nonmetal',
                'melting_point' => 115.21,
                'boiling_point' => 444.67,
                'group' => 16,
                'period' => 3,
                'description' => 'Sulfur is a yellow, crystalline nonmetal. It is found in volcanic regions and is used in the production of sulfuric acid, fertilizers, and matches.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_016_sulfur/element_016_sulfur.glb'
            ],
            [
                'number' => 17,
                'symbol' => 'Cl',
                'name' => 'Chlorine',
                'atomic_mass' => 35.45,
                'category' => 'Halogen',
                'melting_point' => -101.5,
                'boiling_point' => -34.04,
                'group' => 17,
                'period' => 3,
                'description' => 'Chlorine is a greenish-yellow, toxic halogen gas. It is used as a disinfectant in water treatment and in the production of various chemicals.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_017_chlorine/element_017_chlorine.glb'
            ],
            [
                'number' => 18,
                'symbol' => 'Ar',
                'name' => 'Argon',
                'atomic_mass' => 39.948,
                'category' => 'Noble Gas',
                'melting_point' => -189.35,
                'boiling_point' => -185.85,
                'group' => 18,
                'period' => 3,
                'description' => 'Argon is a colorless, odorless, inert noble gas. It is the third most abundant gas in Earth\'s atmosphere and is used in lighting and welding.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_018_argon/element_018_argon.glb'
            ],
            [
                'number' => 19,
                'symbol' => 'K',
                'name' => 'Potassium',
                'atomic_mass' => 39.098,
                'category' => 'Alkali Metal',
                'melting_point' => 63.50,
                'boiling_point' => 759,
                'group' => 1,
                'period' => 4,
                'description' => 'Potassium is a soft, silvery-white, highly reactive alkali metal. It is essential for nerve function and muscle contraction in living organisms.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_019_potassium/element_019_potassium.glb'
            ],
            [
                'number' => 20,
                'symbol' => 'Ca',
                'name' => 'Calcium',
                'atomic_mass' => 40.078,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 842,
                'boiling_point' => 1484,
                'group' => 2,
                'period' => 4,
                'description' => 'Calcium is a gray, alkaline earth metal and the fifth most abundant element in the Earth\'s crust. It is crucial for bones, teeth, and muscle function.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_020_calcium/element_020_calcium.glb'
            ],
            [
                'number' => 21,
                'symbol' => 'Sc',
                'name' => 'Scandium',
                'atomic_mass' => 44.956,
                'category' => 'Transition Metal',
                'melting_point' => 1541,
                'boiling_point' => 2836,
                'group' => 3,
                'period' => 4,
                'description' => 'Scandium is a silvery-white transition metal. It is relatively soft and reactive, used in some high-intensity lighting and to strengthen aluminum alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_021_scandium/element_021_scandium.glb'
            ],
            [
                'number' => 22,
                'symbol' => 'Ti',
                'name' => 'Titanium',
                'atomic_mass' => 47.867,
                'category' => 'Transition Metal',
                'melting_point' => 1668,
                'boiling_point' => 3287,
                'group' => 4,
                'period' => 4,
                'description' => 'Titanium is a strong, lightweight, corrosion-resistant transition metal. It is widely used in aerospace, medical implants, and pigments.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_022_titanium/element_022_titanium.glb'
            ],
            [
                'number' => 23,
                'symbol' => 'V',
                'name' => 'Vanadium',
                'atomic_mass' => 50.942,
                'category' => 'Transition Metal',
                'melting_point' => 1910,
                'boiling_point' => 3407,
                'group' => 5,
                'period' => 4,
                'description' => 'Vanadium is a hard, silvery-gray, ductile transition metal. It is primarily used as an alloying agent to strengthen steel.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_023_vanadium/element_023_vanadium.glb'
            ],
            [
                'number' => 24,
                'symbol' => 'Cr',
                'name' => 'Chromium',
                'atomic_mass' => 51.996,
                'category' => 'Transition Metal',
                'melting_point' => 1907,
                'boiling_point' => 2672,
                'group' => 6,
                'period' => 4,
                'description' => 'Chromium is a hard, shiny, silvery transition metal. It is known for its corrosion resistance and is used in stainless steel and chrome plating.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_024_chromium/element_024_chromium.glb'
            ],
            [
                'number' => 25,
                'symbol' => 'Mn',
                'name' => 'Manganese',
                'atomic_mass' => 54.938,
                'category' => 'Transition Metal',
                'melting_point' => 1246,
                'boiling_point' => 2061,
                'group' => 7,
                'period' => 4,
                'description' => 'Manganese is a hard, brittle, grayish-white transition metal. It is essential in steel production and in some biological enzymes.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_025_manganese/element_025_manganese.glb'
            ],
            [
                'number' => 26,
                'symbol' => 'Fe',
                'name' => 'Iron',
                'atomic_mass' => 55.845,
                'category' => 'Transition Metal',
                'melting_point' => 1538,
                'boiling_point' => 2862,
                'group' => 8,
                'period' => 4,
                'description' => 'Iron is a lustrous, silvery-gray transition metal and the most used metal by mass. It is the main component of steel and essential for hemoglobin in blood.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_026_iron/element_026_iron.glb'
            ],
            [
                'number' => 27,
                'symbol' => 'Co',
                'name' => 'Cobalt',
                'atomic_mass' => 58.933,
                'category' => 'Transition Metal',
                'melting_point' => 1495,
                'boiling_point' => 2927,
                'group' => 9,
                'period' => 4,
                'description' => 'Cobalt is a hard, lustrous, silvery-gray transition metal. It is used in alloys for jet engines, magnetic materials, and vitamin B12.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_027_cobalt/element_027_cobalt.glb'
            ],
            [
                'number' => 28,
                'symbol' => 'Ni',
                'name' => 'Nickel',
                'atomic_mass' => 58.693,
                'category' => 'Transition Metal',
                'melting_point' => 1455,
                'boiling_point' => 2913,
                'group' => 10,
                'period' => 4,
                'description' => 'Nickel is a lustrous, silvery-white transition metal. It is corrosion-resistant and used in alloys like stainless steel and in batteries.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_028_nickel/element_028_nickel.glb'
            ],
            [
                'number' => 29,
                'symbol' => 'Cu',
                'name' => 'Copper',
                'atomic_mass' => 63.546,
                'category' => 'Transition Metal',
                'melting_point' => 1084.62,
                'boiling_point' => 2567,
                'group' => 11,
                'period' => 4,
                'description' => 'Copper is a reddish-orange, ductile, and malleable transition metal.  It is an excellent conductor of heat and electricity, used in wiring, plumbing, and alloys like bronze.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_029_copper/element_029_copper.glb'
            ],
            [
                'number' => 30,
                'symbol' => 'Zn',
                'name' => 'Zinc',
                'atomic_mass' => 65.38,
                'category' => 'Transition Metal',
                'melting_point' => 419.53,
                'boiling_point' => 907,
                'group' => 12,
                'period' => 4,
                'description' => 'Zinc is a bluish-white, lustrous transition metal. It is used in galvanizing steel to prevent corrosion, in batteries, and in alloys like brass.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_030_zinc/element_030_zinc.glb'
            ],
            [
                'number' => 31,
                'symbol' => 'Ga',
                'name' => 'Gallium',
                'atomic_mass' => 69.723,
                'category' => 'Post-Transition Metal',
                'melting_point' => 29.76,
                'boiling_point' => 2204,
                'group' => 13,
                'period' => 4,
                'description' => 'Gallium is a soft, silvery-blue post-transition metal. It has a low melting point and is used in semiconductors and LEDs.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_031_gallium/element_031_gallium.glb'
            ],
            [
                'number' => 32,
                'symbol' => 'Ge',
                'name' => 'Germanium',
                'atomic_mass' => 72.630,
                'category' => 'Metalloid',
                'melting_point' => 938.25,
                'boiling_point' => 2833,
                'group' => 14,
                'period' => 4,
                'description' => 'Germanium is a lustrous, hard metalloid. It is an important semiconductor material, used in transistors and other electronic devices.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_032_germanium/element_032_germanium.glb'
            ],
            [
                'number' => 33,
                'symbol' => 'As',
                'name' => 'Arsenic',
                'atomic_mass' => 74.922,
                'category' => 'Metalloid',
                'melting_point' => 817,
                'boiling_point' => 615,
                'group' => 15,
                'period' => 4,
                'description' => 'Arsenic is a metalloid that exists in several allotropes. It is toxic and was historically used in pesticides.  Now used in semiconductors and wood preservation.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_033_arsenic/element_033_arsenic.glb'
            ],
            [
                'number' => 34,
                'symbol' => 'Se',
                'name' => 'Selenium',
                'atomic_mass' => 78.971,
                'category' => 'Nonmetal',
                'melting_point' => 221,
                'boiling_point' => 685,
                'group' => 16,
                'period' => 4,
                'description' => 'Selenium is a nonmetal with properties intermediate between sulfur and tellurium. It is used in photocells and as a dietary supplement.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_034_selenium/element_034_selenium.glb'
            ],
            [
                'number' => 35,
                'symbol' => 'Br',
                'name' => 'Bromine',
                'atomic_mass' => 79.904,
                'category' => 'Halogen',
                'melting_point' => -7.2,
                'boiling_point' => 58.8,
                'group' => 17,
                'period' => 4,
                'description' => 'Bromine is a reddish-brown liquid halogen. It is corrosive and toxic, used in flame retardants, water purification, and pharmaceuticals.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_035_bromine/element_035_bromine.glb'
            ],
            [
                'number' => 36,
                'symbol' => 'Kr',
                'name' => 'Krypton',
                'atomic_mass' => 83.80,
                'category' => 'Noble Gas',
                'melting_point' => -157.2,
                'boiling_point' => -153.4,
                'group' => 18,
                'period' => 4,
                'description' => 'Krypton is a colorless, odorless, inert noble gas. It is used in lighting, particularly in fluorescent lamps.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_036_krypton/element_036_krypton.glb'
            ],
            [
                'number' => 37,
                'symbol' => 'Rb',
                'name' => 'Rubidium',
                'atomic_mass' => 85.468,
                'category' => 'Alkali Metal',
                'melting_point' => 39.31,
                'boiling_point' => 688,
                'group' => 1,
                'period' => 5,
                'description' => 'Rubidium is a soft, silvery-white, highly reactive alkali metal. It is used in atomic clocks and photocells.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_037_rubidium/element_037_rubidium.glb'
            ],
            [
                'number' => 38,
                'symbol' => 'Sr',
                'name' => 'Strontium',
                'atomic_mass' => 87.62,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 777,
                'boiling_point' => 1382,
                'group' => 2,
                'period' => 5,
                'description' => 'Strontium is a soft, silvery-white alkaline earth metal. It is used in fireworks (red color) and in some nuclear applications.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_038_strontium/element_038_strontium.glb'
            ],
            [
                'number' => 39,
                'symbol' => 'Y',
                'name' => 'Yttrium',
                'atomic_mass' => 88.906,
                'category' => 'Transition Metal',
                'melting_point' => 1526,
                'boiling_point' => 3345,
                'group' => 3,
                'period' => 5,
                'description' => 'Yttrium is a silvery-white transition metal. It is used in lasers, superconductors, and LEDs.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_039_yttrium/element_039_yttrium.glb'
            ],
            [
                'number' => 40,
                'symbol' => 'Zr',
                'name' => 'Zirconium',
                'atomic_mass' => 91.224,
                'category' => 'Transition Metal',
                'melting_point' => 1855,
                'boiling_point' => 4409,
                'group' => 4,
                'period' => 5,
                'description' => 'Zirconium is a strong, corrosion-resistant, grayish-white transition metal. It is used in nuclear reactors, surgical implants, and ceramics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_040_zirconium/element_040_zirconium.glb'
            ],
            [
                'number' => 41,
                'symbol' => 'Nb',
                'name' => 'Niobium',
                'atomic_mass' => 92.906,
                'category' => 'Transition Metal',
                'melting_point' => 2468,
                'boiling_point' => 4744,
                'group' => 5,
                'period' => 5,
                'description' => 'Niobium is a soft, ductile, grayish transition metal. It is used in superconducting magnets and high-strength alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_041_niobium/element_041_niobium.glb'
            ],
            [
                'number' => 42,
                'symbol' => 'Mo',
                'name' => 'Molybdenum',
                'atomic_mass' => 95.95,
                'category' => 'Transition Metal',
                'melting_point' => 2623,
                'boiling_point' => 4639,
                'group' => 6,
                'period' => 5,
                'description' => 'Molybdenum is a hard, silvery-white transition metal with a high melting point. It is used in high-strength steel alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_042_molybdenum/element_042_molybdenum.glb'
            ],
            [
                'number' => 43,
                'symbol' => 'Tc',
                'name' => 'Technetium',
                'atomic_mass' => 98,
                'category' => 'Transition Metal',
                'melting_point' => 2157,
                'boiling_point' => 4265,
                'group' => 7,
                'period' => 5,
                'description' => 'Technetium is a radioactive transition metal. It is the lightest element that is entirely radioactive.  Used in medical imaging.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_043_technetium/element_043_technetium.glb'
            ],
            [
                'number' => 44,
                'symbol' => 'Ru',
                'name' => 'Ruthenium',
                'atomic_mass' => 101.07,
                'category' => 'Transition Metal',
                'melting_point' => 2334,
                'boiling_point' => 4537,
                'group' => 8,
                'period' => 5,
                'description' => 'Ruthenium is a rare, hard, silvery-white transition metal. It is used as a catalyst and in electrical contacts.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_044_ruthenium/element_044_ruthenium.glb'
            ],
            [
                'number' => 45,
                'symbol' => 'Rh',
                'name' => 'Rhodium',
                'atomic_mass' => 102.906,
                'category' => 'Transition Metal',
                'melting_point' => 1964,
                'boiling_point' => 3695,
                'group' => 9,
                'period' => 5,
                'description' => 'Rhodium is a rare, silvery-white, hard transition metal. It is highly corrosion-resistant and used in catalytic converters and jewelry.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_045_rhodium/element_045_rhodium.glb'
            ],
            [
                'number' => 46,
                'symbol' => 'Pd',
                'name' => 'Palladium',
                'atomic_mass' => 106.42,
                'category' => 'Transition Metal',
                'melting_point' => 1554.9,
                'boiling_point' => 2963,
                'group' => 10,
                'period' => 5,
                'description' => 'Palladium is a silvery-white transition metal. It is used in catalytic converters, jewelry, and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_046_palladium/element_046_palladium.glb'
            ],
            [
                'number' => 47,
                'symbol' => 'Ag',
                'name' => 'Silver',
                'atomic_mass' => 107.868,
                'category' => 'Transition Metal',
                'melting_point' => 961.78,
                'boiling_point' => 2162,
                'group' => 11,
                'period' => 5,
                'description' => 'Silver is a soft, white, lustrous transition metal. It has the highest electrical and thermal conductivity of any element and is used in jewelry, currency, and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_047_silver/element_047_silver.glb'
            ],
            [
                'number' => 48,
                'symbol' => 'Cd',
                'name' => 'Cadmium',
                'atomic_mass' => 112.414,
                'category' => 'Transition Metal',
                'melting_point' => 321.07,
                'boiling_point' => 767,
                'group' => 12,
                'period' => 5,
                'description' => 'Cadmium is a soft, bluish-white transition metal. It is toxic and used in batteries, electroplating, and pigments.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_048_cadmium/element_048_cadmium.glb'
            ],
            [
                'number' => 49,
                'symbol' => 'In',
                'name' => 'Indium',
                'atomic_mass' => 114.818,
                'category' => 'Post-Transition Metal',
                'melting_point' => 156.60,
                'boiling_point' => 2072,
                'group' => 13,
                'period' => 5,
                'description' => 'Indium is a soft, silvery-white post-transition metal. It is used in low-melting-point alloys, solders, and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_049_indium/element_049_indium.glb'
            ],
            [
                'number' => 50,
                'symbol' => 'Sn',
                'name' => 'Tin',
                'atomic_mass' => 118.710,
                'category' => 'Post-Transition Metal',
                'melting_point' => 231.93,
                'boiling_point' => 2602,
                'group' => 14,
                'period' => 5,
                'description' => 'Tin is a silvery-white, malleable post-transition metal. It is used in alloys like bronze and solder, and in tin plating to prevent corrosion.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_050_tin/element_050_tin.glb'
            ],
            [
                'number' => 51,
                'symbol' => 'Sb',
                'name' => 'Antimony',
                'atomic_mass' => 121.760,
                'category' => 'Metalloid',
                'melting_point' => 630.63,
                'boiling_point' => 1587,
                'group' => 15,
                'period' => 5,
                'description' => 'Antimony is a lustrous, silvery metalloid. It is used in flame retardants, batteries, and alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_051_antimony/element_051_antimony.glb'
            ],
            [
                'number' => 52,
                'symbol' => 'Te',
                'name' => 'Tellurium',
                'atomic_mass' => 127.60,
                'category' => 'Metalloid',
                'melting_point' => 449.51,
                'boiling_point' => 988,
                'group' => 16,
                'period' => 5,
                'description' => 'Tellurium is a brittle, silvery-white metalloid. It is used in alloys, semiconductors, and as a vulcanizing agent in rubber production.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_052_tellurium/element_052_tellurium.glb'
            ],
            [
                'number' => 53,
                'symbol' => 'I',
                'name' => 'Iodine',
                'atomic_mass' => 126.904,
                'category' => 'Halogen',
                'melting_point' => 113.7,
                'boiling_point' => 184.3,
                'group' => 17,
                'period' => 5,
                'description' => 'Iodine is a lustrous, purple-black nonmetal halogen. It is used as a disinfectant, in iodized salt, and in photography.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_053_iodine/element_053_iodine.glb'
            ],
            [
                'number' => 54,
                'symbol' => 'Xe',
                'name' => 'Xenon',
                'atomic_mass' => 131.29,
                'category' => 'Noble Gas',
                'melting_point' => -111.8,
                'boiling_point' => -108.1,
                'group' => 18,
                'period' => 5,
                'description' => 'Xenon is a colorless, odorless, heavy noble gas. It is used in lighting, lasers, and as an anesthetic.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_054_xenon/element_054_xenon.glb'
            ],
            [
                'number' => 55,
                'symbol' => 'Cs',
                'name' => 'Cesium',
                'atomic_mass' => 132.905,
                'category' => 'Alkali Metal',
                'melting_point' => 28.44,
                'boiling_point' => 671,
                'group' => 1,
                'period' => 6,
                'description' => 'Cesium is a soft, silvery-gold, highly reactive alkali metal. It is used in atomic clocks and photocells.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_055_cesium/element_055_cesium.glb'
            ],
            [
                'number' => 56,
                'symbol' => 'Ba',
                'name' => 'Barium',
                'atomic_mass' => 137.33,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 727,
                'boiling_point' => 1897,
                'group' => 2,
                'period' => 6,
                'description' => 'Barium is a soft, silvery-white alkaline earth metal. It is used in fireworks (green color) and in medical imaging (barium sulfate).',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_056_barium/element_056_barium.glb'
            ],
            [
                'number' => 57,
                'symbol' => 'La',
                'name' => 'Lanthanum',
                'atomic_mass' => 138.905,
                'category' => 'Lanthanide',
                'melting_point' => 920,
                'boiling_point' => 3454,
                'group' => 3,
                'period' => 6,
                'description' => 'Lanthanum is a silvery-white, rare earth metal. It is the first element of the lanthanide series. Used in lighting, lenses, and alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_057_lanthanum/element_057_lanthanum.glb'
            ],
            [
                'number' => 58,
                'symbol' => 'Ce',
                'name' => 'Cerium',
                'atomic_mass' => 140.116,
                'category' => 'Lanthanide',
                'melting_point' => 799,
                'boiling_point' => 3443,
                'group' => 3,
                'period' => 6,
                'description' => 'Cerium is a silvery-white, reactive lanthanide. It is used in catalytic converters, lighter flints, and self-cleaning ovens.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_058_cerium/element_058_cerium.glb'
            ],
            [
                'number' => 59,
                'symbol' => 'Pr',
                'name' => 'Praseodymium',
                'atomic_mass' => 140.908,
                'category' => 'Lanthanide',
                'melting_point' => 935,
                'boiling_point' => 3127,
                'group' => 3,
                'period' => 6,
                'description' => 'Praseodymium is a soft, silvery-white lanthanide. It is used in lasers, magnets, and to give glass a green color.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_059_praseodymium/element_059_praseodymium.glb'
            ],
            [
                'number' => 60,
                'symbol' => 'Nd',
                'name' => 'Neodymium',
                'atomic_mass' => 144.24,
                'category' => 'Lanthanide',
                'melting_point' => 1024,
                'boiling_point' => 3074,
                'group' => 3,
                'period' => 6,
                'description' => 'Neodymium is a silvery lanthanide. It is used in powerful magnets (NdFeB), lasers, and to color glass and ceramics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_060_neodymium/element_060_neodymium.glb'
            ],
            [
                'number' => 61,
                'symbol' => 'Pm',
                'name' => 'Promethium',
                'atomic_mass' => 145,
                'category' => 'Lanthanide',
                'melting_point' => 1045,
                'boiling_point' => 3000,
                'group' => 3,
                'period' => 6,
                'description' => 'Promethium is a radioactive lanthanide. It is used in luminous paints and as a beta-particle source.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_061_promethium/element_061_promethium.glb'
            ],
            [
                'number' => 62,
                'symbol' => 'Sm',
                'name' => 'Samarium',
                'atomic_mass' => 150.36,
                'category' => 'Lanthanide',
                'melting_point' => 1072,
                'boiling_point' => 1791,
                'group' => 3,
                'period' => 6,
                'description' => 'Samarium is a hard, silvery lanthanide. It is used in magnets, lasers, and as a neutron absorber.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_062_samarium/element_062_samarium.glb'
            ],
            [
                'number' => 63,
                'symbol' => 'Eu',
                'name' => 'Europium',
                'atomic_mass' => 151.964,
                'category' => 'Lanthanide',
                'melting_point' => 826,
                'boiling_point' => 1529,
                'group' => 3,
                'period' => 6,
                'description' => 'Europium is a soft, silvery-white lanthanide. It is used in lasers, control rods in nuclear reactors, and to activate phosphors in TV screens.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_063_europium/element_063_europium.glb'
            ],
            [
                'number' => 64,
                'symbol' => 'Gd',
                'name' => 'Gadolinium',
                'atomic_mass' => 157.25,
                'category' => 'Lanthanide',
                'melting_point' => 1313,
                'boiling_point' => 3273,
                'group' => 3,
                'period' => 6,
                'description' => 'Gadolinium is a silvery-white, ductile lanthanide. It has strong magnetic properties and is used in MRI contrast agents and nuclear control rods.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_064_gadolinium/element_064_gadolinium.glb'
            ],
            [
                'number' => 65,
                'symbol' => 'Tb',
                'name' => 'Terbium',
                'atomic_mass' => 158.925,
                'category' => 'Lanthanide',
                'melting_point' => 1356,
                'boiling_point' => 3230,
                'group' => 3,
                'period' => 6,
                'description' => 'Terbium is a silvery-gray lanthanide. It is used in lasers and to activate phosphors, contributing to the green color in fluorescent lamps.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_065_terbium/element_065_terbium.glb'
            ],
            [
                'number' => 66,
                'symbol' => 'Dy',
                'name' => 'Dysprosium',
                'atomic_mass' => 162.500,
                'category' => 'Lanthanide',
                'melting_point' => 1412,
                'boiling_point' => 2562,
                'group' => 3,
                'period' => 6,
                'description' => 'Dysprosium is a silvery-white lanthanide. It is used in lasers, magnets, and nuclear reactor control rods.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_066_dysprosium/element_066_dysprosium.glb'
            ],
            [
                'number' => 67,
                'symbol' => 'Ho',
                'name' => 'Holmium',
                'atomic_mass' => 164.930,
                'category' => 'Lanthanide',
                'melting_point' => 1474,
                'boiling_point' => 2720,
                'group' => 3,
                'period' => 6,
                'description' => 'Holmium is a silvery-white lanthanide. It has strong magnetic properties and is used in lasers and nuclear reactors.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_067_holmium/element_067_holmium.glb'
            ],
            [
                'number' => 68,
                'symbol' => 'Er',
                'name' => 'Erbium',
                'atomic_mass' => 167.259,
                'category' => 'Lanthanide',
                'melting_point' => 1529,
                'boiling_point' => 2868,
                'group' => 3,
                'period' => 6,
                'description' => 'Erbium is a silvery lanthanide. It is used in lasers (especially fiber optic amplifiers) and nuclear technology.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_068_erbium/element_068_erbium.glb'
            ],
            [
                'number' => 69,
                'symbol' => 'Tm',
                'name' => 'Thulium',
                'atomic_mass' => 168.934,
                'category' => 'Lanthanide',
                'melting_point' => 1545,
                'boiling_point' => 1950,
                'group' => 3,
                'period' => 6,
                'description' => 'Thulium is a silvery-gray lanthanide. It is used in portable X-ray devices.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_069_thulium/element_069_thulium.glb'
            ],
            [
                'number' => 70,
                'symbol' => 'Yb',
                'name' => 'Ytterbium',
                'atomic_mass' => 173.054,
                'category' => 'Lanthanide',
                'melting_point' => 824,
                'boiling_point' => 1196,
                'group' => 3,
                'period' => 6,
                'description' => 'Ytterbium is a soft, silvery lanthanide. It is used in lasers and infrared lasers.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_070_ytterbium/element_070_ytterbium.glb'
            ],
            [
                'number' => 71,
                'symbol' => 'Lu',
                'name' => 'Lutetium',
                'atomic_mass' => 174.967,
                'category' => 'Lanthanide',
                'melting_point' => 1663,
                'boiling_point' => 3402,
                'group' => 3,
                'period' => 6,
                'description' => 'Lutetium is a silvery-white lanthanide. It is the last element of the lanthanide series. Used in catalysts and LEDs.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_071_lutetium/element_071_lutetium.glb'
            ],
            [
                'number' => 72,
                'symbol' => 'Hf',
                'name' => 'Hafnium',
                'atomic_mass' => 178.49,
                'category' => 'Transition Metal',
                'melting_point' => 2233,
                'boiling_point' => 4603,
                'group' => 4,
                'period' => 6,
                'description' => 'Hafnium is a silvery-gray transition metal. It is often found with zirconium and is used in nuclear reactors and high-temperature alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_072_hafnium/element_072_hafnium.glb'
            ],
            [
                'number' => 73,
                'symbol' => 'Ta',
                'name' => 'Tantalum',
                'atomic_mass' => 180.948,
                'category' => 'Transition Metal',
                'melting_point' => 3017,
                'boiling_point' => 5458,
                'group' => 5,
                'period' => 6,
                'description' => 'Tantalum is a hard, ductile, gray transition metal. It is highly corrosion-resistant and used in surgical implants and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_073_tantalum/element_073_tantalum.glb'
            ],
            [
                'number' => 74,
                'symbol' => 'W',
                'name' => 'Tungsten',
                'atomic_mass' => 183.84,
                'category' => 'Transition Metal',
                'melting_point' => 3422,
                'boiling_point' => 5555,
                'group' => 6,
                'period' => 6,
                'description' => 'Tungsten is a hard, steel-gray transition metal with the highest melting point of all elements. It is used in light bulb filaments, cutting tools, and high-temperature alloys.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_074_tungsten/element_074_tungsten.glb'
            ],
            [
                'number' => 75,
                'symbol' => 'Re',
                'name' => 'Rhenium',
                'atomic_mass' => 186.207,
                'category' => 'Transition Metal',
                'melting_point' => 3186,
                'boiling_point' => 5596,
                'group' => 7,
                'period' => 6,
                'description' => 'Rhenium is a rare, silvery-white transition metal with a high melting point. It is used in jet engine turbines and catalysts.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_075_rhenium/element_075_rhenium.glb'
            ],
            [
                'number' => 76,
                'symbol' => 'Os',
                'name' => 'Osmium',
                'atomic_mass' => 190.23,
                'category' => 'Transition Metal',
                'melting_point' => 3033,
                'boiling_point' => 5012,
                'group' => 8,
                'period' => 6,
                'description' => 'Osmium is a hard, brittle, bluish-white transition metal. It is one of the densest elements and is used in electrical contacts and catalysts.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_076_osmium/element_076_osmium.glb'
            ],
            [
                'number' => 77,
                'symbol' => 'Ir',
                'name' => 'Iridium',
                'atomic_mass' => 192.217,
                'category' => 'Transition Metal',
                'melting_point' => 2446,
                'boiling_point' => 4428,
                'group' => 9,
                'period' => 6,
                'description' => 'Iridium is a hard, silvery-white transition metal. It is highly corrosion-resistant and used in spark plugs, electrical contacts, and catalysts.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_077_iridium/element_077_iridium.glb'
            ],
            [
                'number' => 78,
                'symbol' => 'Pt',
                'name' => 'Platinum',
                'atomic_mass' => 195.084,
                'category' => 'Transition Metal',
                'melting_point' => 1768.3,
                'boiling_point' => 3825,
                'group' => 10,
                'period' => 6,
                'description' => 'Platinum is a dense, malleable, ductile, precious, silvery-white transition metal. It is used in catalytic converters, jewelry, and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_078_platinum/element_078_platinum.glb'
            ],
            [
                'number' => 79,
                'symbol' => 'Au',
                'name' => 'Gold',
                'atomic_mass' => 196.967,
                'category' => 'Transition Metal',
                'melting_point' => 1064.18,
                'boiling_point' => 2856,
                'group' => 11,
                'period' => 6,
                'description' => 'Gold is a soft, yellow, precious transition metal. It is highly resistant to corrosion and is used in jewelry, currency, and electronics.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_079_gold/element_079_gold.glb'
            ],
            [
                'number' => 80,
                'symbol' => 'Hg',
                'name' => 'Mercury',
                'atomic_mass' => 200.59,
                'category' => 'Transition Metal',
                'melting_point' => -38.83,
                'boiling_point' => 356.7,
                'group' => 12,
                'period' => 6,
                'description' => 'Mercury is a silvery, liquid transition metal. It is toxic and used in thermometers, barometers, and electrical switches. Use is declining due to toxicity.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_080_mercury/element_080_mercury.glb'
            ],
            [
                'number' => 81,
                'symbol' => 'Tl',
                'name' => 'Thallium',
                'atomic_mass' => 204.38,
                'category' => 'Post-Transition Metal',
                'melting_point' => 304,
                'boiling_point' => 1473,
                'group' => 13,
                'period' => 6,
                'description' => 'Thallium is a soft, silvery-white, highly toxic post-transition metal. It was formerly used in rat poisons and is now used in some specialized electronic devices.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_081_thallium/element_081_thallium.glb'
            ],
            [
                'number' => 82,
                'symbol' => 'Pb',
                'name' => 'Lead',
                'atomic_mass' => 207.2,
                'category' => 'Post-Transition Metal',
                'melting_point' => 327.46,
                'boiling_point' => 1749,
                'group' => 14,
                'period' => 6,
                'description' => 'Lead is a soft, heavy, dull gray post-transition metal. It is used in batteries, solder, and radiation shielding.  Its use is restricted due to toxicity.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_082_lead/element_082_lead.glb'
            ],
            [
                'number' => 83,
                'symbol' => 'Bi',
                'name' => 'Bismuth',
                'atomic_mass' => 208.980,
                'category' => 'Post-Transition Metal',
                'melting_point' => 271.4,
                'boiling_point' => 1564,
                'group' => 15,
                'period' => 6,
                'description' => 'Bismuth is a brittle, silvery-white post-transition metal with a slight pinkish tinge. It is used in pharmaceuticals, alloys, and as a lead-free replacement in plumbing.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_083_bismuth/element_083_bismuth.glb'
            ],
            [
                'number' => 84,
                'symbol' => 'Po',
                'name' => 'Polonium',
                'atomic_mass' => 209,
                'category' => 'Post-Transition Metal',
                'melting_point' => 254,
                'boiling_point' => 962,
                'group' => 16,
                'period' => 6,
                'description' => 'Polonium is a rare and highly radioactive post-transition metal. It is used in some specialized industrial applications, but its radioactivity limits its use.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_084_polonium/element_084_polonium.glb'
            ],
            [
                'number' => 85,
                'symbol' => 'At',
                'name' => 'Astatine',
                'atomic_mass' => 210,
                'category' => 'Halogen',
                'melting_point' => 302,
                'boiling_point' => 337,
                'group' => 17,
                'period' => 6,
                'description' => 'Astatine is a highly radioactive halogen. It is the rarest naturally occurring element on Earth.  Its properties are not well-known due to its rarity and radioactivity.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_085_astatine/element_085_astatine.glb'
            ],
            [
                'number' => 86,
                'symbol' => 'Rn',
                'name' => 'Radon',
                'atomic_mass' => 222,
                'category' => 'Noble Gas',
                'melting_point' => -71,
                'boiling_point' => -61.7,
                'group' => 18,
                'period' => 6,
                'description' => 'Radon is a radioactive, colorless, odorless noble gas. It is a health hazard as it can accumulate in buildings and cause lung cancer.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_086_radon/element_086_radon.glb'
            ],
            [
                'number' => 87,
                'symbol' => 'Fr',
                'name' => 'Francium',
                'atomic_mass' => 223,
                'category' => 'Alkali Metal',
                'melting_point' => 27,
                'boiling_point' => 677,
                'group' => 1,
                'period' => 7,
                'description' => 'Francium is a highly radioactive alkali metal. It is extremely rare and unstable, and its properties are not well-known.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_087_francium/element_087_francium.glb'
            ],
            [
                'number' => 88,
                'symbol' => 'Ra',
                'name' => 'Radium',
                'atomic_mass' => 226,
                'category' => 'Alkaline Earth Metal',
                'melting_point' => 700,
                'boiling_point' => 1143,
                'group' => 2,
                'period' => 7,
                'description' => 'Radium is a highly radioactive alkaline earth metal. It was formerly used in cancer treatment but is now largely replaced by less dangerous substances.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_088_radium/element_088_radium.glb'
            ],
            [
                'number' => 89,
                'symbol' => 'Ac',
                'name' => 'Actinium',
                'atomic_mass' => 227,
                'category' => 'Actinide',
                'melting_point' => 1050,
                'boiling_point' => 3200,
                'group' => 3,
                'period' => 7,
                'description' => 'Actinium is a radioactive actinide. It is used in some specialized applications, such as neutron sources.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_089_actinium/element_089_actinium.glb'
            ],
            [
                'number' => 90,
                'symbol' => 'Th',
                'name' => 'Thorium',
                'atomic_mass' => 232.038,
                'category' => 'Actinide',
                'melting_point' => 1750,
                'boiling_point' => 4788,
                'group' => 3,
                'period' => 7,
                'description' => 'Thorium is a radioactive actinide. It is used as a nuclear fuel and in some specialized lighting.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_090_thorium/element_090_thorium.glb'
            ],
            [
                'number' => 91,
                'symbol' => 'Pa',
                'name' => 'Protactinium',
                'atomic_mass' => 231.036,
                'category' => 'Actinide',
                'melting_point' => 1568,
                'boiling_point' => 4000,
                'group' => 3,
                'period' => 7,
                'description' => 'Protactinium is a radioactive actinide. It is rare and has no major commercial uses.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_091_protactinium/element_091_protactinium.glb'
            ],
            [
                'number' => 92,
                'symbol' => 'U',
                'name' => 'Uranium',
                'atomic_mass' => 238.029,
                'category' => 'Actinide',
                'melting_point' => 1132,
                'boiling_point' => 4131,
                'group' => 3,
                'period' => 7,
                'description' => 'Uranium is a radioactive actinide. It is best known for its use as a nuclear fuel in power plants and in nuclear weapons.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_092_uranium/element_092_uranium.glb'
            ],
            [
                'number' => 93,
                'symbol' => 'Np',
                'name' => 'Neptunium',
                'atomic_mass' => 237,
                'category' => 'Actinide',
                'melting_point' => 637,
                'boiling_point' => 4000,
                'group' => 3,
                'period' => 7,
                'description' => 'Neptunium is a radioactive actinide. It is a byproduct of nuclear reactions and is used in some nuclear research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_093_neptunium/element_093_neptunium.glb'
            ],
            [
                'number' => 94,
                'symbol' => 'Pu',
                'name' => 'Plutonium',
                'atomic_mass' => 244,
                'category' => 'Actinide',
                'melting_point' => 639.4,
                'boiling_point' => 3228,
                'group' => 3,
                'period' => 7,
                'description' => 'Plutonium is a radioactive actinide. It is primarily used in nuclear weapons and as a fuel in some nuclear reactors.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_094_plutonium/element_094_plutonium.glb'
            ],
            [
                'number' => 95,
                'symbol' => 'Am',
                'name' => 'Americium',
                'atomic_mass' => 243,
                'category' => 'Actinide',
                'melting_point' => 1176,
                'boiling_point' => 2607,
                'group' => 3,
                'period' => 7,
                'description' => 'Americium is a radioactive actinide. It is used in smoke detectors and as a neutron source.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_095_americium/element_095_americium.glb'
            ],
            [
                'number' => 96,
                'symbol' => 'Cm',
                'name' => 'Curium',
                'atomic_mass' => 247,
                'category' => 'Actinide',
                'melting_point' => 1345,
                'boiling_point' => 3110,
                'group' => 3,
                'period' => 7,
                'description' => 'Curium is a radioactive actinide. It is used in radioisotope thermoelectric generators (RTGs) and nuclear research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_096_curium/element_096_curium.glb'
            ],
            [
                'number' => 97,
                'symbol' => 'Bk',
                'name' => 'Berkelium',
                'atomic_mass' => 247,
                'category' => 'Actinide',
                'melting_point' => 986,
                'boiling_point' => 2900,
                'group' => 3,
                'period' => 7,
                'description' => 'Berkelium is a radioactive actinide. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_097_berkelium/element_097_berkelium.glb'
            ],
            [
                'number' => 98,
                'symbol' => 'Cf',
                'name' => 'Californium',
                'atomic_mass' => 251,
                'category' => 'Actinide',
                'melting_point' => 900,
                'boiling_point' => 1745,
                'group' => 3,
                'period' => 7,
                'description' => 'Californium is a radioactive actinide.  It is a strong neutron emitter, used in nuclear reactors, cancer treatment, and moisture gauges.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_098_californium/element_098_californium.glb'
            ],
            [
                'number' => 99,
                'symbol' => 'Es',
                'name' => 'Einsteinium',
                'atomic_mass' => 252,
                'category' => 'Actinide',
                'melting_point' => 860,
                'boiling_point' => 990,
                'group' => 3,
                'period' => 7,
                'description' => 'Einsteinium is a radioactive actinide. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_099_einsteinium/element_099_einsteinium.glb'
            ],
            [
                'number' => 100,
                'symbol' => 'Fm',
                'name' => 'Fermium',
                'atomic_mass' => 257,
                'category' => 'Actinide',
                'melting_point' => 1527,
                'boiling_point' => null,
                'group' => 3,
                'period' => 7,
                'description' => 'Fermium is a radioactive actinide. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_100_fermium/element_100_fermium.glb'
            ],
            [
                'number' => 101,
                'symbol' => 'Md',
                'name' => 'Mendelevium',
                'atomic_mass' => 258,
                'category' => 'Actinide',
                'melting_point' => 827,
                'boiling_point' => null,
                'group' => 3,
                'period' => 7,
                'description' => 'Mendelevium is a radioactive actinide. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_101_mendelevium/element_101_mendelevium.glb'
            ],
            [
                'number' => 102,
                'symbol' => 'No',
                'name' => 'Nobelium',
                'atomic_mass' => 259,
                'category' => 'Actinide',
                'melting_point' => 827,
                'boiling_point' => null,
                'group' => 3,
                'period' => 7,
                'description' => 'Nobelium is a radioactive actinide. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_102_nobelium/element_102_nobelium.glb'
            ],
            [
                'number' => 103,
                'symbol' => 'Lr',
                'name' => 'Lawrencium',
                'atomic_mass' => 262,
                'category' => 'Actinide',
                'melting_point' => 1627,
                'boiling_point' => null,
                'group' => 3,
                'period' => 7,
                'description' => 'Lawrencium is a radioactive actinide. It is the last element of the actinide series and is primarily used for research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_103_lawrencium/element_103_lawrencium.glb'
            ],
            [
                'number' => 104,
                'symbol' => 'Rf',
                'name' => 'Rutherfordium',
                'atomic_mass' => 267,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 4,
                'period' => 7,
                'description' => 'Rutherfordium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_104_rutherfordium/element_104_rutherfordium.glb'
            ],
            [
                'number' => 105,
                'symbol' => 'Db',
                'name' => 'Dubnium',
                'atomic_mass' => 270,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 5,
                'period' => 7,
                'description' => 'Dubnium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_105_dubnium/element_105_dubnium.glb'
            ],
            [
                'number' => 106,
                'symbol' => 'Sg',
                'name' => 'Seaborgium',
                'atomic_mass' => 271,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 6,
                'period' => 7,
                'description' => 'Seaborgium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_106_seaborgium/element_106_seaborgium.glb'
            ],
            [
                'number' => 107,
                'symbol' => 'Bh',
                'name' => 'Bohrium',
                'atomic_mass' => 272,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 7,
                'period' => 7,
                'description' => 'Bohrium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_107_bohrium/element_107_bohrium.glb'
            ],
            [
                'number' => 108,
                'symbol' => 'Hs',
                'name' => 'Hassium',
                'atomic_mass' => 270,
                'category' => 'Transition Metal',
                'melting_point' => 1827,
                'boiling_point' => null,
                'group' => 8,
                'period' => 7,
                'description' => 'Hassium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_108_hassium/element_108_hassium.glb'
            ],
            [
                'number' => 109,
                'symbol' => 'Mt',
                'name' => 'Meitnerium',
                'atomic_mass' => 276,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 9,
                'period' => 7,
                'description' => 'Meitnerium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_109_meitnerium/element_109_meitnerium.glb'
            ],
            [
                'number' => 110,
                'symbol' => 'Ds',
                'name' => 'Darmstadtium',
                'atomic_mass' => 281,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 10,
                'period' => 7,
                'description' => 'Darmstadtium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_110_darmstadtium/element_110_darmstadtium.glb'
            ],
            [
                'number' => 111,
                'symbol' => 'Rg',
                'name' => 'Roentgenium',
                'atomic_mass' => 280,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 11,
                'period' => 7,
                'description' => 'Roentgenium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_111_roentgenium/element_111_roentgenium.glb'
            ],
            [
                'number' => 112,
                'symbol' => 'Cn',
                'name' => 'Copernicium',
                'atomic_mass' => 285,
                'category' => 'Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 12,
                'period' => 7,
                'description' => 'Copernicium is a synthetic, radioactive transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_112_copernicium/element_112_copernicium.glb'
            ],
            [
                'number' => 113,
                'symbol' => 'Nh',
                'name' => 'Nihonium',
                'atomic_mass' => 286,
                'category' => 'Post-Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 13,
                'period' => 7,
                'description' => 'Nihonium is a synthetic, radioactive post-transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_113_nihonium/element_113_nihonium.glb'
            ],
            [
                'number' => 114,
                'symbol' => 'Fl',
                'name' => 'Flerovium',
                'atomic_mass' => 289,
                'category' => 'Post-Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 14,
                'period' => 7,
                'description' => 'Flerovium is a synthetic, radioactive post-transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_114_flerovium/element_114_flerovium.glb'
            ],
            [
                'number' => 115,
                'symbol' => 'Mc',
                'name' => 'Moscovium',
                'atomic_mass' => 290,
                'category' => 'Post-Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 15,
                'period' => 7,
                'description' => 'Moscovium is a synthetic, radioactive post-transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_115_moscovium/element_115_moscovium.glb'
            ],
            [
                'number' => 116,
                'symbol' => 'Lv',
                'name' => 'Livermorium',
                'atomic_mass' => 293,
                'category' => 'Post-Transition Metal',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 16,
                'period' => 7,
                'description' => 'Livermorium is a synthetic, radioactive post-transition metal. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_116_livermorium/element_116_livermorium.glb'
            ],
            [
                'number' => 117,
                'symbol' => 'Ts',
                'name' => 'Tennessine',
                'atomic_mass' => 294,
                'category' => 'Halogen',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 17,
                'period' => 7,
                'description' => 'Tennessine is a synthetic, radioactive halogen. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_117_tennessine/element_117_tennessine.glb'
            ],
            [
                'number' => 118,
                'symbol' => 'Og',
                'name' => 'Oganesson',
                'atomic_mass' => 294,
                'category' => 'Noble Gas',
                'melting_point' => null,
                'boiling_point' => null,
                'group' => 18,
                'period' => 7,
                'description' => 'Oganesson is a synthetic, radioactive noble gas. It is primarily used in scientific research.',
                'model_path' => 'https://storage.googleapis.com/search-ar-edu/periodic-table/element_118_oganesson/element_118_oganesson.glb'
            ],
        ]);
    }
}
